vim.opt.completeopt = { "menu", "menuone", "noinsert", "noselect", "popup", "fuzzy" }
-- TODO a kind of "plugin" for hover on completion item
-- local completed_word = ""
-- local orig_util_open_floating_preview = vim.lsp.util.open_floating_preview
-- function vim.lsp.util.open_floating_preview(contents, syntax, opts, ...)
--     opts = opts or {}
--     local pum = vim.fn.pum_getpos()
--     if vim.tbl_isempty(pum) then
--         return orig_util_open_floating_preview(contents, syntax, opts, ...)
--     end
--
--     local max_width = vim.api.nvim_win_get_width(0) - pum.col - pum.width - 10
--
--     opts.offset_x = pum.width - #completed_word
--     P("completed_word")
--     P(completed_word)
--     P(#completed_word)
--     opts.max_width = max_width
--     P(opts)
--     return orig_util_open_floating_preview(contents, syntax, opts, ...)
-- end
-- local gid = vim.api.nvim_create_augroup("complete", { clear = true })
-- vim.api.nvim_create_autocmd("CompleteChanged", {
--     group = gid,
--     callback = function(ev)
--         local data = vim.deepcopy(vim.v.event)
--         completed_word = data.completed_item.word
--         vim.lsp.buf.hover()
--         -- completed_word =   ""
--     end,
-- })
