-- https://github.com/microsoft/vscode/blob/main/src/vs/base/common/codicons.ts
-- go to the above and then enter <c-v>u<unicode> and the symbol should appear
-- or go here and upload the font file: https://mathew-kurian.github.io/CharacterMap/
-- find more here: https://www.nerdfonts.com/cheat-sheet

return {
    lsp = {
        Class = "",
        Color = "",
        Constant = "",
        Constructor = "",
        Copilot = "",
        Enum = "",
        EnumMember = "",
        Event = "",
        Field = "",
        File = "",
        Folder = "",
        Function = "󰊕",
        Interface = "",
        Keyword = "",
        Method = "m",
        Module = "",
        Operator = "",
        Property = "",
        Reference = "",
        Snippet = "",
        Struct = "",
        Text = "",
        TypeParameter = "",
        Unit = "",
        Value = "",
        Variable = "",
    },
    documents = {
        FileContents = "",
        Folder = "",
        OpenFolder = "",
        EmptyFolder = "",
    },
    git = {
        Add = "",
        Mod = "",
        Remove = "",
        Ignore = "",
        Rename = "",
        Branch = "",
        Unmerged = "",
        Unstaged = "",
        Staged = "✓",
        Untracked = "★",
    },
    ui = {
        Check = "󰄬",
        CheckAll = "󰄭",
        Lock = "",
        FilledLock = "",
        Square = "",
        Bug = "",
        FoldClosed = "",
        FoldOpen = "",
        Expanded = "▾",
        Collapsed = "▸",
        Guide = "┊",
        LeftHalf = "",
        RightHalf = "",
        Laptop = "",
        Animations = {
            -- keep those odd
            Fill = {
                "  ",
                "_ ",
                "__",
                "▁▁",
                "▂▂",
                "▃▃",
                "▄▄",
                "▅▅",
                "▆▆",
                "▇▇",
                "██",
            },
        },
    },
    lines = {
        Corner = "└",
        Edge = "│",
    },
    diagnostics = {
        Error = "",
        Warning = "",
        Information = "",
        Hint = "󰛨",
    },
    misc = {
        Neovim = "",
    },
    characters = {
        Nbsp2 = "○",
        SlopeDown = "◣",
        SlopeUp = "◢",
        Tab = "▷",
        Trail = "·",
        EmptyTriangle = "󰼛",
        Caret = "󱞩",
    },
    oss = {
        Linux = "",
        Windows = "",
        Mac = "",
    },
}
