-- https://github.com/microsoft/vscode/blob/main/src/vs/base/common/codicons.ts
-- go to the above and then enter <c-v>u<unicode> and the symbold should appear
-- or go here and upload the font file: https://mathew-kurian.github.io/CharacterMap/
-- find more here: https://www.nerdfonts.com/cheat-sheet

return {
    kind = {
        Class = "",
        Color = "",
        Constant = "",
        Constructor = "",
        Copilot = "",
        Enum = "",
        EnumMember = "",
        Event = "",
        Field = "",
        File = "",
        Folder = "",
        Function = "󰊕",
        Interface = "",
        Keyword = "",
        Method = "m",
        Module = "",
        Operator = "",
        Property = "",
        Reference = "",
        Snippet = "",
        Struct = "",
        Text = "",
        TypeParameter = "",
        Unit = "",
        Value = "",
        Variable = "",
    },
    documents = {
        File = "",
        Files = "",
        FileContents = "",
        SymlinkFile = "",
        Folder = "",
        OpenFolder = "",
        EmptyFolder = "",
        EmptyOpenFolder = "",
        SymlinkFolder = "",
    },
    git = {
        Add = "",
        Mod = "",
        Remove = "",
        Ignore = "",
        Rename = "",
        Diff = "",
        Repo = "",
        Branch = "",
        Commit = "",
        Unmerged = "",
        Unstaged = "",
        Staged = "✓",
        Untracked = "★",
        Deleted = "✗",
    },
    ui = {
        Lock = "",
        FilledLock = "",
        Circle = "",
        BigCircle = "",
        BigUnfilledCircle = "",
        SmallCircle = "●",
        Square = "",
        CircleDot = "",
        NewFile = "",
        SearchBig = "",
        Up = "",
        Down = "",
        Project = "",
        Dashboard = "",
        Bug = "",
        Code = "",
        Telescope = "",
        Gear = "",
        Gears = " ",
        Package = "",
        List = "",
        SignIn = "",
        Check = "",
        Fire = "",
        BookMark = "",
        ChevronRight = "",
        Table = "",
        Calendar = "",
        FoldClosed = "",
        FoldOpen = "",
        Expanded = "▾",
        Collapsed = "▸",
        Guide = "┊",
        LeftHalf = "",
        RightHalf = "",
        FilledTerminal = "",
        Terminal = "",
        Laptop = "",
        Animations = {
            -- keep those odd
            Fill = { "  ", "_ ", "__", "▁▁", "▂▂", "▃▃", "▄▄", "▅▅", "▆▆", "▇▇", "██" },
            ThinFill = { "_", "▁", "▂", "▃", "▄", "▅", "▆", "▇", "█" },
        },
    },
    lines = {
        Corner = "└",
        Edge = "│",
    },
    diagnostics = {
        Error = "",
        Warning = "",
        Information = "",
        Question = "",
        Hint = "󰛨",
        Attention = "",
    },
    misc = {
        Bsd = "",
        Neovim = "",
        NullCircle = "",
        Squirrel = " ",
        Tag = "",
        Watch = "",
    },
    languages = {
        Lua = "",
    },
    characters = {
        Eol = "↵",
        Nbsp = "␣",
        Nbsp2 = "○",
        SlopeDown = "◣",
        SlopeUp = "◢",
        Tab = "▷",
        Trail = "·",
    },
    oss = {
        Linux = "",
        Windows = "",
        Mac = "",
    },
    dap = {
        StepInto = "󰆹",
        StepOut = "󰆸",
        StepOver = " ",
        RunLast = " ",
        Close = "󰅙 ",
    },
}
